### ISSUE TITLE
Stats are incorrect

### ISSUE THREAD

**Issue by saschakovac** [iffypixy/faceitperf#3]
Alot of the time, the stats listed on faceitperf (both the overall ratings, and the ADR, KAST, etc) are just bogus and completely incorrect. Try to have it parse correct statistics?

**Comment by iffypixy** [comment]
> Alot of the time, the stats listed on faceitperf (both the overall ratings, and the ADR, KAST, etc) are just bogus and completely incorrect. Try to have it parse correct statistics?

If you look really closely on the website, you'll see that there's a disclaimer above those "metrics" stating that they are not exact figures, rather approximate estimation. These stats are not provided by FACEIT API.
